### ISSUE TITLE
P1 HTML time

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#11]
我们在这里使用语义标签: `<time>` 如何?

### 示例:
`<p>The concert starts at <time>20:00</time>.</p>`

引用:  [time](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/time)

**Comment by Y4m1n** [comment]
你的引用是英文的哟 https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/time 这是中文的
