### ISSUE TITLE
通用：移除代码注释

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#13]
## 代码规范：
我们最好移除这段文字注释掉的代码
可以参考：
- http://softwareengineering.stackexchange.com/questions/45378/is-commented-out-code-really-always-bad
- http://softwareengineering.stackexchange.com/questions/190096/can-commented-out-code-be-valuable-documentation

**Comment by Y4m1n** [comment]
>The code that have been commented out, without any information on why can really make people reading your code confused. Is this broken code that needs to be fixed? Old code that has been replaced? Why is that code there?  

某篇文章里的 帮助学生理解为什么要移除

**Comment by WillBeethoven** [comment]
@evestorm @PoBlue 有什么建议吗？

**Comment by PoBlue** [comment]
注释掉的代码可以删除掉，删除掉能使项目更整洁，阅读起来更加地流畅！

在编程中，我们可以养成一种尽量用代码解释代码的思维，不要过多地依赖评论去解释代码，才能写出易于理解的代码：

## 例子🌰

### 利用注释解释
```
//n的平方根与牛顿 - 拉夫逊逼近
r = n / 2;
while ( abs( r - (n/r) ) > t ) {
    r = 0.5 * ( r + (n/r) );
}

System.out.println( "r = " + r );
```

### 利用代码的函数名字进行解释的
```
private double SquareRootApproximation(n) {
   r = n / 2;
   while ( abs( r - (n/r) ) > t ) {
       r = 0.5 * ( r + (n/r) );
   }
   return r;
}

System.out.println( "r = " + SquareRootApproximation(r) );
```

# 详细请参考：
- [Coding Without Comments](https://blog.codinghorror.com/coding-without-comments/)
