### ISSUE TITLE
P2 CSS Padding 语法

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#17]
我们可以简化这里的写法：

### Padding 语法
```
/* 适用于四个边 */
padding: 1em;

/* 上下 | 左右 */
padding: 5% 10%;

/* 上 | 左右 | 下 */
padding: 1em 2em 2em; 

/* 上 | 右 | 下 | 左 */
padding: 2px 1em 0 1em;

/* 全局值 */
padding: inherit;
padding: initial;
padding: unset;
```

**Comment by evestorm** [comment]
这个
/* 上 | 下 | 左 | 右 */
padding: 2px 1em 0 1em;
是不是有点问题，难道不应该是 上右下左的顺序吗？
<img width="911" alt="comp" src="https://cloud.githubusercontent.com/assets/18142851/25438984/b5626cea-2acd-11e7-91b7-e562c9f24b07.png">

**Comment by WillBeethoven** [comment]
感谢指出，已修正！

**Comment by evestorm** [comment]
可以啦
