### ISSUE TITLE
P2 CSS 空格 :

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#18]
## 代码规范：
别忘了在属性和值之间插入空行：

### 例子:
 `height:3px;`

### 变为:

 `height: 3px;`

引用：[属性名标点](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/前端工程师纳米学位样式指南%20-%20CSS.md#属性名标点)

**Comment by evestorm** [comment]
### 建议

根据 [Udacity 前端 CSS 代码风格: 属性名标点](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%88%E7%BA%B3%E7%B1%B3%E5%AD%A6%E4%BD%8D%E6%A0%B7%E5%BC%8F%E6%8C%87%E5%8D%97%20-%20CSS.md#属性名标点) :

> 所有属性名冒号后均需添加空格，但属性和冒号间不加空格，以增加连贯性。

#### 不推荐：

```css
font-weight:bold;
padding : 0;
margin :0;
```

#### 推荐：

```css
font-weight: bold;
padding: 0; 
margin: 0;
```

**Comment by WillBeethoven** [comment]
@evestorm 
还要：**开发者对开发者的建议** 吗？
