### ISSUE TITLE
P2 CSS 空格 {

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#19]
## 代码规范：
为了保持可读性，我们推荐在 `selector` 和 `{` 之间留有一个空格。

**Comment by evestorm** [comment]
## 开发者 对 开发者 建议
根据 [Udacity 前端 CSS 代码风格: 声明区标点](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%88%E7%BA%B3%E7%B1%B3%E5%AD%A6%E4%BD%8D%E6%A0%B7%E5%BC%8F%E6%8C%87%E5%8D%97%20-%20CSS.md#声明区标点) :
>  最后一个选择符和声明区起始处的左大括号之间需加空格。

### 不推荐：

```css
.image{
   ...
}
```

### 推荐：

```css
.image {
	...
}
```

**Comment by WillBeethoven** [comment]
@evestorm 认同！
@PoBlue 有更好的解法吗？或者有什么提升建议吗？

**Comment by PoBlue** [comment]
很赞，**推荐** 下面那个 `.image` 里面的 `...` 和前面的缩进一样就OK了，三个空格～
```
.image {
   ...
}
```

**Comment by WillBeethoven** [comment]
## 开发者对开发者的建议
根据 [Udacity 前端 CSS 代码风格: 声明区标点](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/%E5%89%8D%E7%AB%AF%E5%B7%A5%E7%A8%8B%E5%B8%88%E7%BA%B3%E7%B1%B3%E5%AD%A6%E4%BD%8D%E6%A0%B7%E5%BC%8F%E6%8C%87%E5%8D%97%20-%20CSS.md#声明区标点) :
>  最后一个选择符和声明区起始处的左大括号之间需加空格。

### 不推荐：

```css
.image{
   ...
}
```

### 推荐：

```css
.image {
   ...
}
```
