### ISSUE TITLE
P2 CSS 缩进

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#21]
## 代码规范：
>整个文件中的缩进应保持前后一致，使用 Tab、2个空格或4个空格都可以，但需保持前后一致。

引用：[缩进](https://github.com/udacity/frontend-nanodegree-styleguide-zh/blob/master/前端工程师纳米学位样式指南%20-%20CSS.md#缩进)

**Comment by evestorm** [comment]
过

**Comment by WillBeethoven** [comment]
@evestorm 如果经过审核的话就把标签换下啦

![screen shot 2017-05-07 at 1 04 21 pm](https://cloud.githubusercontent.com/assets/14329786/25778064/b50400a0-3325-11e7-8a2d-fe94870bee5a.png)

**Comment by evestorm** [comment]
@WillBeethoven  😃 好的
