### ISSUE TITLE
P6 JS pizzasNum

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#30]
根据浏览设备的大小，背景图中的 Pizza 最少应为 24 个, 也就意味着横排的值 `cols` 不是固定的. 更好的方法就是适应屏幕的需求，动态的计算 Pizza 的数量。

**提示**: 如果计算列的话，我们可以使用屏幕的 [height](https://developer.mozilla.org/en-US/docs/Web/API/Screen/height) 属性，然后把宽和高相乘。

**引用**:
https://developer.mozilla.org/en-US/docs/Web/API/Screen/height
http://www.w3schools.com/jsref/prop_screen_height.asp
https://developer.mozilla.org/en-US/docs/Web/API/Screen/width
http://tripleodeon.com/2011/12/first-understand-your-screen/
http://ryanve.com/lab/dimensions/

**Note**: 记得把做出的改变写在 `README.md` 里～

**Comment by evestorm** [comment]
下面是我找到的一位reviewer审阅给出的指导，觉得很赞，收藏了：
![屏幕快照 2017-04-18 上午3.13.27.png](https://udacity-reviews-uploads.s3.amazonaws.com/_attachments/31443/1492456357/_____2017-04-18___3.13.27.png)

生成 pizza 的数量太多了，有 200 多个，有很多的没有显示在浏览器的窗口中。因此可以考虑减少 pizza 数量的个数来达到优化流畅度的目的。

我们可以计算一下窗口中需要的 pizza 个数，进而设置合理的个数：

![屏幕快照 2017-04-18 上午3.22.13.png](https://udacity-reviews-uploads.s3.amazonaws.com/_attachments/31443/1492457190/_____2017-04-18___3.22.13.png)

如上图所示，我们生成 pizza 的一个大致的简图。那么实际上我们需要的 pizza 个数：

```javascript
需要的 pizza 行数 = 窗口高度 / s

实际需要的 pizza 个数 = 需要的 pizza 行数 * 列数(cols)
```

以上就是计算出个数的伪代码，浏览器窗口高度可以通过上网搜索了解如何获取～

**Comment by PoBlue** [comment]
赞成，因为是我写的😎

**Comment by WillBeethoven** [comment]
@PoBlue  Awesome!

**Comment by evestorm** [comment]
@PoBlue   hah 猜到了~  👍
