### ISSUE TITLE
P1 HTML H 标签的使用

### ISSUE THREAD

**Issue by WillBeethoven** [Udanite/FEND-Review-Library-Zh_CN#8]
[亲自试一试？](http://www.w3school.com.cn/tiy/t.asp?f=html_headers)

>一般来说，<h1>用来修饰网页的主标题，<h2>表示一个段落的标题，<h3>表示段落的小节标题，因为，搜索引擎需要在一堆文本中明白它写的是什么，所以，它也依照人们的阅读习惯，首先寻找文章的标题，然而，不像人们那样可以迅速确定标题是什么，搜索引擎是“盲人”，所以，使用<h>标签就指导搜索引擎标题在那里，便于它们迅速掌握文本大意。标题（H1-H6）标签是采用关键词的重要地方，这个标签应该包括文本中最重要的关键词，Google算法就指出，这个<h>和</h>直接的题头文字，一定比其它地方的文章具备更重要的意义，但是，过分的使用容易产生不利的影响

引用：[h1 标签](http://baike.baidu.com/item/h1标签#2)

**Comment by WillBeethoven** [comment]
仔细观察一下，模版中的段落标题是否要稍微小一点呢？

- 测试不同 `h` 标签的效果: [W3School](http://www.w3school.com.cn/tiy/t.asp?f=html_headers)
- 在合适的情景选用合适的标签: [标题元素](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Heading_Elements)

搜索引擎会把文章中出现的 `<h1>`到 `<h6>` 标签来作为文章的结构与主次，从而进行索引，所以我们要谨慎使用呀。

**Comment by Y4m1n** [comment]
搜索引擎会把文章中出现的` <h1>`到 `<h6> `标签来作为文章的结构与主次，从而进行索引，所以我们要谨慎使用:

>避免跳过某级标题：始终要从 <h1> 开始，接下来使用 <h2> 等等。
>避免重复在一个页面上使用 <h1>，<h1> 应该用来表示页面的标题，其他的标题当从 <h2> 开始。

你可以尝试在最顶部编写一个由 `<h1>` 包裹的文档标题，例如： `<h1>Class notes</h1>`
然后将第本页面其他所有` <h*> `作标签降级处理。

**Comment by Y4m1n** [comment]
搜索引擎会把文章中出现的` <h1>`到 `<h6> `标签来作为文章的结构与主次，从而进行索引，所以我们要谨慎使用:

>避免跳过某级标题：始终要从 `<h1>` 开始，接下来使用 `<h2>` 等等。
>避免重复在一个页面上使用 `<h1>`，`<h1>` 应该用来表示页面的标题，其他的标题当从 `<h2>` 开始。

你可以尝试在最顶部编写一个由 `<h1>` 包裹的文档标题，例如： `<h1>Class notes</h1>`
然后将第本页面其他所有` <h*> `作标签降级处理。

**Comment by evestorm** [comment]
@Y4m1n  的建议很棒 👍

**Comment by WillBeethoven** [comment]
@evestorm 那就用 @Y4m1n 作为标准吧～
